FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY --exclude=**/test* . .

EXPOSE 3000

ARG TYPE=local
ARG DEBUG_PORT=9229
ENV TYPE=${TYPE}
ENV DEBUG_PORT=${DEBUG_PORT}

CMD ["/bin/sh", "-c", "/app/docker/run.debug.sh"]
