import { HttpStatus } from "@nestjs/common";
import { DomainErrorCode } from '../errors/domain.error';

const map: Record<DomainErrorCode, HttpStatus> = {
  CREDENTIAL_MISMATCH: HttpStatus.UNAUTHORIZED,
  INSUFFICIENT_PRIVILEGES: HttpStatus.FORBIDDEN,
  INVALID_TOKEN: HttpStatus.UNAUTHORIZED,
  TOKEN_EXPIRED: HttpStatus.UNAUTHORIZED,
  TOKEN_REVOKED: HttpStatus.UNAUTHORIZED,
  USER_NOT_FOUND: HttpStatus.NOT_FOUND,
  USERNAME_TAKEN: HttpStatus.CONFLICT,
  ENV_NOT_FOUND: HttpStatus.NOT_FOUND,
  SCRIPT_NOT_FOUND: HttpStatus.NOT_FOUND,
  SCRIPT_VERSION_NOT_FOUND: HttpStatus.NOT_FOUND,
  NON_DRAFT_SCRIPT_VERSION_UPDATE: HttpStatus.CONFLICT,
  NON_DRAFT_SCRIPT_VERSION_PUBLISH: HttpStatus.CONFLICT,
  SCRIPT_RUN_NOT_FOUND: HttpStatus.NOT_FOUND,
  SCRIPT_RUN_REMOVE_STATUS: HttpStatus.CONFLICT,
  SCRIPT_RUN_CANCEL_STATUS: HttpStatus.CONFLICT,
  SCRIPT_RUN_REEXECUTE_STATUS: HttpStatus.CONFLICT,
  UNPUBLISHED_SCRIPT_RUN_ATTEMPT: HttpStatus.CONFLICT
}

export function mapDomainErrorStatus(code: string) {
  return map[code] ?? HttpStatus.INTERNAL_SERVER_ERROR;
}